### PR TITLE
Bug/#31 WAR file support

### PR DESCRIPTION
**Pull request by spyhunter99**
for everything except signatures

### CODE REVIEW

**Comment by chrisdoyle** [comment]
This is a great addition.  Just gotta reconcile the conflicts and it'll be ready to merge in!

**Comment by spyhunter99** [comment]
you did all the hard work, i just copied and pasted stuff lol

**Comment by spyhunter99** [comment]
this may have uncovered another issue, because of the signing before building bit, you have to run `gradle publish` several times until everything is built and signed, or run `gradle build`, then `gradle publish`

**Comment by spyhunter99** [comment]
merge 35 first

**Pull request merged**
